before:
  hooks:
    - go mod tidy

builds:
  - id: autobrr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/autobrr/main.go
    binary: autobrr
    ldflags:
      - -s -w

archives:
  - id: autobrr
    builds:
      - autobrr
    files:
      - none*
    replacements:
      amd64: x86_64

release:
  prerelease: auto

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
